name: 'Build and Deploy SLM'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: app/terraform

    - name: Create ECR Repository (Targeted)
      run: terraform apply -target=aws_ecr_repository.main -auto-approve
      working-directory: app/terraform

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push to ECR
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/tfm-slm:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/tfm-slm:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Terraform Apply (Complete)
      run: terraform apply -auto-approve -var="docker_image_tag=${{ github.sha }}"
      working-directory: app/terraform
