name: 'Docker Image CI'

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: tfm-slm:test
        cache-from: type=gha,scope=tfm-slm-cache
        cache-to: type=gha,scope=tfm-slm-cache
